dir = "src/services"
lang = "TS"
organization_id = "ginger-society"
portal_refs_file = "src/shared/references.ts"
service_type = "Portal"

[services]

[portals_refs]

[urls]
dev = "http://localhost:3001"
prod = "https://example.com"
stage = "https://example.com"
